name: SkyStream Engine Auto-Run

on:
  schedule:
    - cron: '0 * * * *'  # Har 1 ghante mein khud chalega
  workflow_dispatch:      # Manual "Run workflow" button rahega

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          SCRIPT_URL: ${{ secrets.SCRIPT_URL }}
        run: python main.py
